# Generated by Django 4.2.1 on 2023-05-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250)),
                ('book_year', models.DateField(max_length=4)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
